stages:
  - pre

pre:
  stage: pre
  image: maven:3.8.5-openjdk-11-slim
  scripts:
    - echo PRE
    - echo DONE!
  artifacts:
    paths: ''
    reports:
      sast:
        paths:
         - 'spotbugsSarif.json'
         - 'sast.json'
      dast:
        paths:
         - 'report.json'
