image: maven:3.8.5-openjdk-11-slim
stages:
  - stage
  - destroy
  - create
  - obliterate

cache:
  paths:
    - .m2/repository/
    - core/target/
    - desktop/target/

job 1:
  stage: stage
  scripts:
    - bash script.sh
  artifacts:
      reports:
        paths: 'target/spotbugsSarif.json'
        base_dir: 'src/main/java'
      name: hui
      paths:
        - 'pom.xml'

job 11:
  stage: stage
  scripts:
    - ./script.sh
  tags:
    - docker

job 2:
  stage: destroy
  scripts:
    - mvn -Dmaven.repo.local=.m2/repository -Dstyle.color=always clean compile

job 3:
  stage: create
  scripts:
    - ./script.sh

job 4:
  stage: obliterate
  scripts:
    - ./script.sh
