stages:
    pre

pre:
    stage: pre
    image: maven:3.8.5-openjdk-11-slim
    scripts:
      - echo DONE!
    artifacts:
        baseDir: ''
        name: wtf
        reports:
            paths: 'light.sarif'
        paths: 'light.sarif'
