stages:
  - pre
  - dast

cache:
  paths:
    - /zap

pre:
  stage: pre
  image: maven:3.8.5-openjdk-11-slim
  scripts:
    - echo PRE
    - echo BLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLA
    - echo DONE!

dast:
  stage: dast
  image: owasp/zap2docker-stable
  scripts:
    - echo DAST
    - touch /zap/dast-report.json
    - zap.sh -addoninstall reports -cmd -autorun /builds/adminuser/dsadsa/zap.yaml
    - echo DONE!
  artifacts:
    reports:
      paths: '/zap/dast-report.json'
    name: report
    paths:
      - 'pom.xml'
