image: maven:3.8.5-openjdk-11-slim
stages:
  - stage
  - destroy
  - create
  - obliterate

cache:
  paths:
    - .m2/repository/
    - core/target/
    - desktop/target/

job 1:
  stage: stage
  scripts:
    - bash script.sh
    - mkdir target
    - cat spotbugsSarif.json > target/spotbugsSarif.json
  artifacts:
      reports:
        paths: 'target/spotbugsSarif.json'
      name: hui
      paths:
        - 'pom.xml'
