stages:
  - pre
  - dast

cache:
  paths:
    - .m2/repository/
    - core/target/
    - desktop/target/

pre:
  stage: pre
  image: maven:3.8.5-openjdk-11-slim
  scripts:
    - echo PRE
    - echo BLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLA
    - echo DONE!

dast:
  stage: dast
  image: softwaresecurityproject/zap-stable
  scripts:
    - echo DAST
    - zap.sh -cmd -addonupdate -addoninstall reports
    - echo DONE!
  artifacts:
    reports:
      paths: 'target/dast-report.json'
    name: report
    paths:
      - 'pom.xml'
