image: maven:3.8.5-openjdk-11-slim
stages:
  - stage
  - destroy
  - create
  - dast
  - obliterate

cache:
  paths:
    - .m2/repository/
    - core/target/
    - desktop/target/

job 2:
  stage: dast
  scripts:
    - echo DAST
    - mkdir -p target
    - cat dast.json > target/dast.json
  artifacts:
    reports:
      paths: 'target/dast.json'
    name: hui
    paths:
      - 'pom.xml'
