image: maven:3.8.5-openjdk-11-slim
stages:
  - dast

cache:
  paths:
    - .m2/repository/
    - core/target/
    - desktop/target/

dast:
  image:
    name: softwaresecurityproject/zap-weekly:latest
  stage: dast
  scripts:
    - echo DAST
    - mkdir -p target
    - ls
    - echo DONE!
  artifacts:
    reports:
      paths: 'target/dast.json'
    name: hui
    paths:
      - 'pom.xml'
