stages:
  - pre
  - dast

pre:
  stage: pre
  image: maven:3.8.5-openjdk-11-slim
  scripts:
    - echo PRE
    - echo BLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLABLA
    - echo DONE!

dast:
  stage: dast
  image: owasp/zap2docker-stable
  scripts:
    - echo DAST
    - pwd
    - ls
    - echo $wrk
    - touch /zap/dast-report.json
    - zap.sh -addoninstall reports -cmd -autorun /builds/adminuser/dsadsa/zap.yaml
    - echo DONE!
    - cp /zap/dast-report.json dast-report.json
  artifacts:
    reports:
      paths: dast-report.json
    name: report
